#+TITLE: An Interactive Web based "TODO" list.
#+TODO: TODO(t) SCHEDULED(@/!) WAIT(w@/!) INPROGRESS(p@/!) DELEGATED(l@) | CANCELED(c!) DONE(d@/!)

* Introduction
  I started learning from Semmy Purewel's  /Learning Web App Development/ a
  while ago,  by now have forgotten the details. I will restart learning from
  the book again, and write a web based TODO list.

* What TODO

** Review book up to chapter 4. 
   SCHEDULED <2017-05-09 Di>
   CANCELLED <2019-05-12 So>
   It has been too long. Now we have other plans

* Log
  To follow the development of a project I will have to record when I have
  developed its various parts. These will be saved in the section Log. It makes
  sense for this section to be towards the top, after the *TODO* section.
  
* <2019-05-12 So>
  Start over to use Scala on the back-end and React on the front-end.
  



* Giter8
  [[http://www.foundweekends.org/giter8/][Giter8]] is a command line tool to generate files and directories form templates 
  published on Github or any other git repository. Implemented in Scala and run 
  through the ~sbt launcher~, it can produce output for any purpose.

** Conscript
   Some scripts to install stuff from Github. ~Giter8~ was installed using
   [[http://www.foundweekends.org/giter8/setup.html][~Conscript~]].

   
* Server related
  - Kill server :: If ~localhost:9000~ is occupied, check the ~PID~ using
  #+begin_src
  lsof -i:9000
  #+end_src
  and ~kill <PID>~
  - Guice :: Add ~guice~ to ~libraryDependencies~ in ~build.sbt~ to get an
             /application loader/. Otherwise the application does not load!
             
